name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [ 'amd64', 'arm64' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Setup Node.js 22.14
        uses: actions/setup-node@v6
        with:
          node-version: '22.14'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Build
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-power-${{ matrix.arch }}
          path: dist
          retention-days: 90
